### ISSUE TITLE
Tagconnect orientation differs between revb6 files and actual PCB

### ISSUE THREAD

**Issue by PetteriAimonen** [ruuvi/ruuvitag_hw#3]
First of all, thanks for the great product! I'll just point out this minor difference that I noticed.

The revb6 files from this repository look like this, with a single tagconnect hole towards the edge:
![ruuvitag_rev6](https://user-images.githubusercontent.com/922265/67199022-e75c1c80-f408-11e9-9e9a-dbf8657d7fbb.png)

But the PCB looks like this, with two tagconnect holes towards the edge:
![ruuvitag_pcb](https://user-images.githubusercontent.com/922265/67199034-efb45780-f408-11e9-8b85-d4c1401c49d5.png)

The reason I noticed this is because I designed a small add-on pcb that solders onto the testpads:
![ruuvitag_addon](https://user-images.githubusercontent.com/922265/67199145-3013d580-f409-11e9-8028-9a0c700a2a73.png)

**Comment by laurijamsa** [comment]
Orientation of the connector has changed after B6. See the latest B7.1 project design files for more info.
