### ISSUE TITLE
KiCad v7/v6 "rescue symbols" error opening schematic (b8)

### ISSUE THREAD

**Issue by SensorPlay** [ruuvi/ruuvitag_hw#4]
Opening the project file > schematic generates "rescue symbols" error (screencap)

<img width="959" alt="rescueSymbols" src="https://user-images.githubusercontent.com/53378730/219882934-539f7965-88e7-4f17-9f0e-5464700a6c58.PNG">

I thought this may be a new version error, so I rolled back to 5.1.8 KiCad (the version on the schematic pdf), but same errors are generated.

I'm not a super experienced KiCad user (Altium), but usually with library errors there's a library file that needs to be imported?

Cool project btw.

**Comment by laurijamsa** [comment]
These aren't actually errors but the app just notifies you that some old symbols may break the schematic when opened. I just tried to open the same project using KiCad 7 and it opened just fine. Download this schematic component library and place it in same folder with the ruuvitag_hw folder and then relative library paths of the project should work correctly: https://github.com/ruuvi/kicad-library
